# macOS sample for adding the simulator to your firmware's platformio.ini.
# Apple Silicon defaults are enabled. Intel Mac users should remove -arch arm64
# and change Homebrew paths from /opt/homebrew to /usr/local if needed.

[env:simulator]
platform = native
build_flags =
  -std=gnu++2a
  -lSDL2
  -arch arm64
  -I/opt/homebrew/include
  -L/opt/homebrew/lib
  -Wno-c++11-narrowing
  -DSIMULATOR
  -DCROSSPOINT_VERSION=\"dev-simulator\"
  -DENABLE_SERIAL_LOG
  -DLOG_LEVEL=2
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DMINIZ_NO_ZLIB_COMPATIBLE_NAMES=1
  -DXML_GE=0
  -DXML_CONTEXT_BYTES=1024
  -DUSE_UTF8_LONG_NAMES=1
  -DPNG_MAX_BUFFERED_PIXELS=16416
  -DDISABLE_FS_H_WARNING=1
  -DDESTRUCTOR_CLOSES_FILE=1
lib_ignore = hal, PNGdec, JPEGDEC
extra_scripts =
  pre:scripts/gen_i18n.py
  pre:scripts/git_branch.py
  pre:scripts/build_html.py
  scripts/run_simulator.py
lib_deps =
  simulator_mock=https://github.com/uxjulia/crosspoint-simulator
  bblanchon/ArduinoJson @ 7.4.2
  ricmoo/QRCode @ ^0.0.1
  links2004/WebSockets @ 2.7.3
